### ISSUE TITLE
Branch - Change from master to main

### ISSUE THREAD

**Issue by valentinajemuovic** [techexcellenceio/airline-tracking#1]

**Comment by GuillaumeTaffin** [comment]
@valentinacupac Hi, it seems I don't have write rights on this repo. I don't know if you can give me a role that allows me to manage the repo
Thanks

**Comment by valentinajemuovic** [comment]
@GuillaumeTaffin I now changed from "Write" to "Maintainer". Feel free to let me know if it works or not.

**Comment by GuillaumeTaffin** [comment]
@valentinacupac Well it seems I cannot overwrite the main branch.
I should have looked before... Here they say people with "admin" role can rename branches.
 --> https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/renaming-a-branch

That's a bit sad that maintainers cannot rename the branch... but whatever xD
I really don't mind being admin on the repo, but anyway if you juste prefer rename the branch it's here ^^ --> https://github.com/techexcellenceio/airline-tracking/branches

**Comment by valentinajemuovic** [comment]
@GuillaumeTaffin thanks for the information, I wasn't aware of those differences, so now I did the renaming.

Message from GitHub was:

```
The default branch has been renamed!
master is now named main

If you have a local clone, you can update it by running the following commands.

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
